language: ruby
rvm:
  - 2.3.1
addons:
  chrome: stable
before_install:
  - gem install bundler -v 1.12.5
  - wget http://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - rm chromedriver_linux64.zip
  - sudo mv -f chromedriver /usr/local/bin/
  - sudo chmod +x /usr/local/bin/chromedriver
  - google-chrome-stable --headless --no-sandbox
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: KWyxLcTNDKLaUjXelwyTNPtB/HcolK02mqrpJVwgA7OW6htXqMW+HBVcIizxzNNKouFgkfr3rqwthRNSRF0RtoEEeLihkx4VPGq7INe3hw8A5+urLchBFgzslYX/dMuoBazifXr4xTX2qeD53yjr2KBlPU8p8a0EhwPYjkcD12A/f9gNehyoLSRLALH6HCfBOJngqRsEdhsHGYuz8DHE5nb8B+4g+POmQlx8Yapm7Z/8axtXQNZk9yt3ZeujLr5AC8SeFEpTJlFc8yVffrTh6ALFznnYZ/H2DuNQWgjx1oEiKCBDYlKNmy6JJXB07LCpCcaaWLdezHsB/eMYY9M5WDGMhagzmavbhQzUtse/NvXgbpRDeW2ODREriPSOklMP830YIvqHrYqA/3kaz474ChZaSGRzeIEpMTcC6VjtDluzo+VhJkfo2pGQnACuoKXI0fCCtK++Nw9QGIem4k1ro4bjNDel7F+CfAlFDF+MCTKQBdg04gX6fcNKJptuvKtT9/DTC0hte2/ytzGVBw5qzSU9m1nAy52QzJUPldfB96h8CkwoM2oYZTIqdHG5/tbBFPNWjC1H3CgYJ/mGcH1Vs2pTIRXYGBbDdOR6UeIMEj4k8NwErW7xJJPCv9qQCatE5235I9aX/zRAHowUkmkvtHhHt33ItBkqfKPchluRlIY=
  gem: activeadmin_jobs
  on:
    tags: true
    repo: platanus/activeadmin_jobs
