# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec9aa883d1567ae0983fb818c4acb77ac448c54ca9c15b0e25fd8dd1f1fdeee9c0c6b74dcaf42c77b5e1dcd560ca4251408c0284e400190b5ba5c30aae8514ae

test:
  secret_key_base: dc0d4a5c6b29e7be344a0e92ad18958b507cab2e3b680c6f33109112ea31758285f828dc838b65bc78f2760d8f763f108fb332b82723203dd3579caae2410cfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
